export interface Person {
    Nom : string,
    Prenom : string,
    CIN : string,
    Tel : string,
    Adresse : string,
    Role : string,
    Num_bureau : string,
    // salaire : string,
    image : string,
}
export interface Technicien {
    Nom : string,
    Prenom : string,
    CIN : string,
    Tel : string,
    Adresse : string,
    uid : string,
    matricule : string,
    date_naissance : string,
    date_embauche : string,
    date_depart : string,
    salaire : string,
    service : string,
    grade : string,
    image : string,
}

export interface Employee {
    Nom : string,
    Prenom : string,
    CIN : string,
    Tel : string,
    Adresse : string,
    uid : string,
    Num_bureau : string,
    // salaire : string,
    image : string,
}

export interface helper {
    Nom : string,
    Prenom : string,
    CIN : string,
    Tel : string,
    Adresse : string,
    uid : string,
    matricule : string,
    date_naissance : string,
    date_embauche : string,
    date_depart : string,
    salaire : string,
    service : string,
    grade : string,
    image : string,
}

export interface intervention {
    Nom : string,
    Prenom : string,
    CIN : string,
    Tel : string,
    Adresse : string,
    uid : string,
    matricule : string,
    date_naissance : string,
    date_embauche : string,
    date_depart : string,
    salaire : string,
    service : string,
    grade : string,
    image : string,
}